version: '3'

services: 
    db:
        image: postgres
    migration:
        build: .
        command: python manage.py migrate
        volumes:
            - .:/usr/src/app
        depends_on: 
            - db
        environment:
            - "POSTGRES_HOST_AUTH_METHOD=trust"
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/usr/src/app
        ports:
             - "8000:8000"
        depends_on: 
            - db
            - migration
            