version: '3.6'

services: 
    db:
        image: postgres
        environment:
            - "POSTGRES_HOST_AUTH_METHOD=trust"
        
 

    migration:
        build: .
        command: python manage.py migrate
        volumes:
            - .:/usr/src/app
        depends_on: 
            - db
        

    web:
        build: .    
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/usr/src/app
        ports:
             - "8000:8000"
        depends_on: 
            - db
            - migration
            